export default [
    {
        name: 'name',
        required: true,
        label: 'Название',
        align: 'left',
        field: row => row.name,
        format: val => `${val}`,
        sortable: true,
    },
    {
        required: true,
        name: 'discount_card_number',
        align: 'left',
        label: 'Номер дисконтной карты',
        field: 'discount_card_number',
    },
    {
        required: true,
        name: 'bank_accounts',
        align: 'left',
        label: 'Банк аккаунт',
        field: 'bank_accounts',
    },
    {
        required: true,
        name: 'groups',
        align: 'left',
        label: 'Группа',
        field: 'groups',
        type: 'select',
    },
    {
        required: true,
        name: 'status',
        align: 'left',
        label: 'Статус',
        field: 'status',
    },
    {
        name: 'description',
        align: 'left',
        label: 'Описание',
        field: 'description',
    },
    {
        name: 'phone',
        align: 'left',
        label: 'Телефон',
        field: 'phone',
    },
    {
        name: 'fax',
        align: 'left',
        label: 'Факс',
        field: 'fax',
    },
    {
        name: 'email',
        align: 'left',
        label: 'E-mail',
        field: 'email',
    },
    {
        name: 'address',
        align: 'left',
        label: 'Адрес',
        field: 'address',
    },
    {
        name: 'address_comment',
        align: 'left',
        label: 'Комментарий к адресу',
        field: 'address_comment',
    },
    {
        name: 'comment',
        align: 'left',
        label: 'Комментарий',
        field: 'comment',
    },
    {
        name: 'code',
        align: 'left',
        label: 'Код',
        field: 'code',
    },
    {
        name: 'external_code',
        align: 'left',
        label: 'Внешний код',
        field: 'external_code',
    },
    {
        name: 'contacts',
        align: 'left',
        label: 'Контакты',
        field: 'contacts',
    },
    {
        name: 'contractor_type',
        align: 'left',
        label: 'Тип Контрагента',
        field: 'contractor_type',
    },
    {
        name: 'inn',
        align: 'left',
        label: 'ИНН',
        field: 'inn',
    },
    {
        name: 'kpp',
        align: 'left',
        label: 'КПП',
        field: 'kpp',
    },
    {
        name: 'okpo',
        align: 'left',
        label: 'ОКПО',
        field: 'okpo',
    },
    {
        name: 'department',
        align: 'left',
        label: 'Департамент',
        field: 'department',
    },
];
