export default [
    {
        required: true,
        name: 'number',
        align: 'left',
        label: 'Номер',
        field: 'number',
    },
    {
        required: true,
        name: 'warehouse',
        align: 'left',
        label: 'Склад',
        field: 'warehouse',
    },
    {
        required: true,
        name: 'product',
        align: 'left',
        label: 'Товар',
        field: 'product',
    },
    {
        required: true,
        name: 'quantity',
        align: 'left',
        label: 'Количество',
        field: 'quantity',
    },
    {
        required: true,
        name: 'project',
        align: 'left',
        label: 'Проект',
        field: 'project',
    },
    {
        required: true,
        name: 'patient',
        align: 'left',
        label: 'Пациент',
        field: 'patient',
    },
    {
        name: 'created_at',
        align: 'left',
        label: 'Дата',
        field: 'created_at',
    },

    {
        name: 'comment',
        align: 'left',
        label: 'Комментарии',
        field: 'comment',
    },
    {
        name: 'expenses',
        align: 'left',
        label: 'Расход',
        field: 'expenses',
    },
    {
        name: 'comment',
        align: 'left',
        label: 'Комментарий',
        field: 'comment',
    },
    {
        name: 'approved',
        align: 'left',
        label: 'Подверждение',
        field: 'approved',
    },
];
